# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: src/projects/testApi3/webAPI/Dockerfile
    ports:
      - 5151:5151
    restart: always
    depends_on:
      - mssqldb
    
  mssqldb: 
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - MSSQL_PID=Developer
      - MSSQL_AUTHENTICATION=ActiveDirectoryPassword
      - SA_PASSWORD: "sAdmin123"
      - ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

